import { KeyData } from "./types";

export const nordicLayout: KeyData[][] = [
  // Row 0: Function row — generally hit with pinky or top row reach
  [
    { label: "Esc", finger: "L5" },
    { label: "F1", finger: "L5" },
    { label: "F2", finger: "L4" },
    { label: "F3", finger: "L3" },
    { label: "F4", finger: "L2" },
    { label: "F5", finger: "L2" },
    { label: "F6", finger: "R2" },
    { label: "F7", finger: "R2" },
    { label: "F8", finger: "R3" },
    { label: "F9", finger: "R4" },
    { label: "F10", finger: "R5" },
    { label: "F11", finger: "R5" },
    { label: "F12", finger: "R5" },
  ],
  // Row 1
  [
    { label: "§", finger: "L5" },
    { label: "1", finger: "L5" },
    { label: "2", finger: "L4" },
    { label: "3", finger: "L3" },
    { label: "4", finger: "L2" },
    { label: "5", finger: "L2" },
    { label: "6", finger: "R2" },
    { label: "7", finger: "R2" },
    { label: "8", finger: "R3" },
    { label: "9", finger: "R4" },
    { label: "0", finger: "R5" },
    { label: "+", finger: "R5" },
    { label: "´", finger: "R5" },
    { label: "⌫", w: 2, finger: "R5" },
  ],
  // Row 2
  [
    { label: "Tab", w: 1.5, finger: "L5" },
    { label: "Q", finger: "L5" },
    { label: "W", finger: "L4" },
    { label: "E", finger: "L3" },
    { label: "R", finger: "L2" },
    { label: "T", finger: "L2" },
    { label: "Y", finger: "R2" },
    { label: "U", finger: "R2" },
    { label: "I", finger: "R3" },
    { label: "O", finger: "R4" },
    { label: "P", finger: "R5" },
    { label: "Å", finger: "R5" },
    { label: "^", w: 2.7, finger: "R5" },
  ],
  // Row 3
  [
    { label: "Caps", w: 2.2, finger: "L5" },
    { label: "A", finger: "L5" },
    { label: "S", finger: "L4" },
    { label: "D", finger: "L3" },
    { label: "F", finger: "L2" },
    { label: "G", finger: "L2" },
    { label: "H", finger: "R2" },
    { label: "J", finger: "R2" },
    { label: "K", finger: "R3" },
    { label: "L", finger: "R4" },
    { label: "Ö", finger: "R5" },
    { label: "Ä", finger: "R5" },
    { label: "*", finger: "R5" },
    { label: "↵", w: 1, finger: "R5" },
  ],
  // Row 4
  [
    { label: "Shift", w: 1, finger: "L5" },
    { label: "<", finger: "L5" },
    { label: "Z", finger: "L5" },
    { label: "X", finger: "L4" },
    { label: "C", finger: "L3" },
    { label: "V", finger: "L2" },
    { label: "B", finger: "L2" },
    { label: "N", finger: "R2" },
    { label: "M", finger: "R2" },
    { label: ",", finger: "R3" },
    { label: ".", finger: "R4" },
    { label: "-", finger: "R5" },
    { label: "Shift", w: 3.3, finger: "R5" },
  ],
  // Row 5
  [
    { label: "Ctrl", w: 1.8, finger: "L5" },
    { label: "Win", w: 1.5, finger: "L5" },
    { label: "Alt", w: 1.5, finger: "L5" },
    { label: "Space", w: 6, finger: "Thumb" },
    { label: "AltGr", w: 1.5, finger: "R5" },
    { label: "Fn", w: 1.5, finger: "R5" },
    { label: "Ctrl", w: 1.5, finger: "R5" },
  ],
];

export const simplelayout: KeyData[][] = [
  [{ label: "Esc" }, { label: "F1" }, { label: "F2" }],
  [{ label: "`" }, { label: "1" }, { label: "2" }, { label: "3" }],
  [{ label: "Tab" }, { label: "Q" }, { label: "W" }, { label: "E" }],
  [{ label: "Shift" }, { label: "Z" }, { label: "X" }, { label: "C" }],
  [
    { label: "Ctrl" },
    { label: "Alt" },
    { label: "Space", w: 5 },
    { label: "Alt" },
    { label: "Ctrl" },
  ],
];
